import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * Nick Martinez and Andrew Corchado - Single File Inheritence
 * Created by Nick Martinez on 9/3/16.
 */
public class Tool extends InventoryItem
{
    private static final String insertQuery = "INSERT INTO " + DB_TABLE_NAME +
            " (upc, manufacturerID, price, description, length, batteryPowered, " +
            "numberInStrip, numberInBox, type) " +
            "VALUES (?,?,?,?,null,null,null,null,?);";
    private static final String selectQuery = "SELECT * FROM " + DB_TABLE_NAME +
            " WHERE id = (?);";

    protected String description;

    /**
     * Creation constructor. Initializes a new Tool.
     * @param id - the id of the tool
     * @param upc - the upc of the tool
     * @param manufacturerID - the manufacturer ID of the tool
     * @param price - the price of the tool
     * @param description - the description of the tool
     */
    public Tool(int id, String upc, int manufacturerID, int price, String description)
    {
        super(id, upc, manufacturerID, price);
        this.description = description;
    }

    /**
     * Finder constructor for Tool.
     * @param id - the id of the Tool
     */
    public Tool(int id)
    {
        super(id);
    }

    /** Maps Tool to database */
    @Override
    protected void insert()
    {
        // id is generated by MySQL
        try(    Connection connection = DBConnection.getConnection();
                PreparedStatement stmt = connection.prepareStatement(insertQuery) )
        {
            stmt.setString(1, upc);
            stmt.setInt(2, manufacturerID);
            stmt.setInt(3, price);
            stmt.setString(4, description);
            stmt.setString(5, getClassType());

            stmt.executeUpdate();
        } catch (SQLException exception)
        {
            exception.printStackTrace();
        }
    }

    /**
     *
     * @param id
     */
    @Override
    protected void find(int id)
    {
        try(    Connection connection = DBConnection.getConnection();
                PreparedStatement stmt = connection.prepareStatement(selectQuery) ) {
            stmt.setInt(1, id);

            ResultSet rs = stmt.executeQuery();
            id = rs.getInt("id");
            upc = rs.getString("upc");
            manufacturerID = rs.getInt("manufacturerID");
            price = rs.getInt("price");
            description = rs.getString("description");
        } catch (SQLException exception)
        {
            exception.printStackTrace();
        }
    }

    /**
     * Returns the description of this tool.
     * @return - the description
     */
    public String getDescription()
    {
        return description;
    }

    /**
     * Returns the class type.
     * @return - the class type
     */
    @Override
    public String getClassType()
    {
        return "Tool";
    }

}
